name: filmique
description: "Aplikacija za filme"

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  fluttertoast: ^8.2.8
  provider: ^6.0.0
  # firebase_core: ^3.6.0
  # firebase_auth: ^5.3.1

  cupertino_icons: ^1.0.8


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:


  uses-material-design: true
